language: java
jdk:
- openjdk8
after_success:
- bash <(curl -s https://codecov.io/bash)
global:
  env:
    secure: B/Ntp70mY7AZa8c5A47m/7rdkRuRlC/0/el5A+tk+hB+SixdTs1ucIjrk+vAlrvBDxtYXSxp7ipcXYo3WxrSh3SlFmOzFVydT/Ri2MapPleO3zVLQOO67LE9bsL4poy6JScasigruMt1LBQ+Z7wTHSNJ+CvS07UN5YUIF3vA12g=
