

name: Build

on: [push, pull_request]

jobs:
  run-tests:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [8, 11, 17, 21]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'
      - name: Run the Maven verify phase
        run: ./gradlew build --no-daemon
